<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle("Shopping Cart")->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body style="padding:20px;">
<div class="container">
    <div class="row">
        <a href="<?php echo $this->url('home') ?>"><img src="//static.uprinting.com/bootstrap/img/uprinting-logo.svg"
                                                        alt="UPrinting: Online Printing Services" width="220"
                                                        height="60"/></a>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-10">
            <div style="font-size:18px; font-weight:bold;">
            </div>
        </div>
    </div>
</div>
<hr/>
<div class="container">
    <?php echo $this->content; ?>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
